name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.3
        with:
          version: 10.28.2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.13.0"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: './docs'
      - name: Build docs
        run: pnpm run docs:build
        working-directory: './docs'
      - name: scp
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST_NEKO }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORDNEKO }}
          source: 'docs/.vitepress/dist/*'
          target: '/tmp/'
      - name: script
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST_NEKO }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORDNEKO }}
          script: |
            mkdir -p /root/docker_data/caddy/caddy_data/static_site/abv4/
            rm -rf /root/docker_data/caddy/caddy_data/static_site/abv4/*
            mv /tmp/docs/.vitepress/dist/* /root/docker_data/caddy/caddy_data/static_site/abv4/
            rm -rf /tmp/docs/
